echo sanghu
./asserter.sh AnyswapV5ERC20
./asserter.sh AssetTransfer
./asserter.sh Ballot
./asserter.sh BasicProvenance
./asserter.sh ClockBoxContract
./asserter.sh DigitalLocker
./asserter.sh ERC20
./asserter.sh EStack
./asserter.sh MiraNft
./asserter.sh RefrigeratedTransportation
./asserter.sh RoomThermostat
./asserter.sh SimpleECR20
./asserter.sh SimpleMarketplace
./asserter.sh TESTDONTBUY
./asserter.sh Token
./asserter.sh TokenVesting
./asserter.sh escrow
./asserter.sh ptest
./asserter.sh shibabread
./asserter.sh AIRBets
./asserter.sh Animalia
./asserter.sh Benu
./asserter.sh BERNIE
./asserter.sh BurnableERC20
./asserter.sh ChinaCoin
./asserter.sh COINNetwork
./asserter.sh CyberFox
./asserter.sh DogeMojo
./asserter.sh DogeRocket
./asserter.sh eMuppy
./asserter.sh eNew
./asserter.sh FrontRunner
./asserter.sh Galaxium
./asserter.sh goldinu
./asserter.sh kia_quiz
./asserter.sh KizunaInu
./asserter.sh Kyuseishu
./asserter.sh LILY
./asserter.sh Lunar
./asserter.sh MayoOcho
./asserter.sh MJCoin_Token
./asserter.sh PipiCoin
./asserter.sh PONY
./asserter.sh PORCUPINE
./asserter.sh PROGEV2
./asserter.sh RBC
./asserter.sh RIAS
./asserter.sh Ryujin
./asserter.sh salvador
./asserter.sh SATURNITE
./asserter.sh ShibaAstronaut
./asserter.sh ShibaJail
./asserter.sh ShibaKiyo
./asserter.sh ShibaSamurai
./asserter.sh SOTH
./asserter.sh StarNFTProxy
./asserter.sh Thicc
./asserter.sh TOAD
./asserter.sh UniswapV3MigratorProxy
./asserter.sh VamprireDoge
./asserter.sh WickedCraniums
./asserter.sh wLitiSale
./asserter.sh WrappedToken
./asserter.sh Address
./asserter.sh GOLIATH
./asserter.sh HOTDOGE
./asserter.sh HotinuFinance
./asserter.sh KOALA
./asserter.sh payments
./asserter.sh eMastiff
cd Results
./run-extract.sh
cd ..
